# Fase 1 — Definición del proyecto

## Análisis exploratorio de procedimientos sancionatorios de la Superintendencia del Medio Ambiente

**Curso:** MCDI500 — Magíster en Ciencia de Datos e Inteligencia Artificial  
**Evaluación:** Sumativa 1 — Fases 1 y 2  
**Fase:** F1 — Definición del proyecto y configuración inicial del entorno reproducible

## 1. Contextualización del proyecto

La Superintendencia del Medio Ambiente (SMA) dispone de información pública asociada a procedimientos sancionatorios derivados de actividades de fiscalización y cumplimiento ambiental. Estos registros contienen antecedentes administrativos y territoriales que permiten caracterizar el comportamiento de los procedimientos iniciados por la institución.

El presente proyecto busca aplicar herramientas de Ciencia de Datos para organizar, explorar y posteriormente procesar este conjunto de información mediante un flujo de trabajo reproducible. La implementación considera el uso de Python, Jupyter Notebook, Pandas, NumPy y Git/GitHub, de acuerdo con las buenas prácticas de documentación, control de versiones y trazabilidad definidas para el curso.

Durante la Fase 1 se establece la definición del problema, los objetivos, el alcance y la configuración inicial del entorno. Las tareas de limpieza, transformación y validación del conjunto de datos serán desarrolladas posteriormente en la Fase 2.

## 2. Definición de la problemática

Los datos abiertos asociados a procedimientos sancionatorios de la Superintendencia del Medio Ambiente constituyen una fuente de información relevante para estudiar el comportamiento de la actividad sancionatoria ambiental en Chile. Sin embargo, disponer de los registros no implica que estos se encuentren inmediatamente preparados para un análisis reproducible.

El conjunto de datos requiere inicialmente ser reconocido en cuanto a su estructura, variables y características generales y, posteriormente, ser sometido a un proceso sistemático de exploración, evaluación de calidad, limpieza y transformación.

La problemática del proyecto consiste, por tanto, en establecer un flujo reproducible de Ciencia de Datos que permita preparar y analizar los registros de procedimientos sancionatorios de la SMA, manteniendo la trazabilidad entre los datos originales, las decisiones de procesamiento y los resultados obtenidos.

A partir de este proceso se busca generar una base técnicamente consistente que permita, en las fases posteriores del proyecto, caracterizar los procedimientos sancionatorios e identificar patrones relevantes presentes en los datos.s datos.

## 3. Pregunta central y preguntas de apoyo

### Pregunta central

**¿Qué factores se asocian a multas de mayor magnitud, expresadas en UTA, en los procedimientos sancionatorios de la Superintendencia del Medio Ambiente?**

### Preguntas de apoyo

1. ¿Cómo se distribuye la variable `MultaTotalUTA` dentro del universo de procedimientos que presentan una sanción confirmada?

2. ¿Qué relación presentan las variables explicativas seleccionadas en el proyecto con la magnitud de las multas?

3. ¿Qué problemas de calidad, valores faltantes o inconsistencias deben considerarse antes de analizar dichas asociaciones?

4. ¿Qué decisiones de preprocesamiento y transformación son necesarias para disponer de un conjunto de datos técnicamente consistente para las fases posteriores? de datos?

## 4. Objetivo general

Desarrollar un flujo reproducible de Ciencia de Datos para la preparación y análisis de los procedimientos sancionatorios publicados por la Superintendencia del Medio Ambiente, utilizando Python y herramientas del ecosistema científico, con el propósito de obtener un conjunto de datos consistente, trazable y adecuado para la identificación posterior de patrones relevantes.

## 5. Objetivos específicos

1. Documentar la fuente, estructura y características generales del conjunto de datos utilizado en el proyecto.

2. Configurar un entorno de trabajo reproducible mediante Python, Jupyter Notebook, gestión explícita de dependencias y control de versiones con Git/GitHub.

3. Diagnosticar la calidad del conjunto de datos mediante la evaluación de dimensiones, tipos de variables, valores faltantes, duplicados y otras posibles inconsistencias.

4. Implementar en la Fase 2 un pipeline funcional de limpieza y transformación, justificando cada decisión a partir del diagnóstico previo de los datos.

5. Validar el conjunto de datos resultante y dejarlo preparado como entrada reproducible para las fases posteriores de análisis y visualización.

## 6. Alcance y limitaciones

El proyecto analizará los procedimientos sancionatorios contenidos en la copia del conjunto de datos de la Superintendencia del Medio Ambiente seleccionada por el equipo, utilizando como variable de interés la magnitud de las multas expresada mediante `MultaTotalUTA`.

El análisis se orientará a estudiar la posible asociación entre la magnitud de las multas y las variables explicativas seleccionadas en el proyecto, considerando únicamente la información disponible en el conjunto de datos.

Durante las Fases 1 y 2 se abordarán la definición del problema, configuración del entorno reproducible, reconocimiento del conjunto de datos, diagnóstico de calidad, limpieza, transformación y validación técnica.

Quedan fuera del alcance de estas fases la inferencia causal, la predicción de futuras sanciones y cualquier generalización que exceda la cobertura temporal, administrativa y estructural de la copia del conjunto de datos utilizada.

Los análisis y visualizaciones posteriores se desarrollarán en las Fases 3 y 4 a partir del conjunto de datos procesado y validado generado en la Fase 2.royecto.

## 7. Supuestos y decisiones pendientes

### Supuestos

- La copia descargada del conjunto de datos representa el estado de la fuente oficial en la fecha de obtención que será registrada en el README del proyecto.
- La ausencia de un valor en `MultaTotalUTA` no será interpretada automáticamente como un problema de calidad de datos, ya que puede corresponder a procedimientos que no presentan una multa aplicable.
- Las variables `RegionNombre` y `CategoriaEconomicaNombre` serán consideradas conceptualmente como variables categóricas nominales, independientemente del número de categorías que presenten.
- El archivo almacenado en `data/raw/` se conservará sin modificaciones durante todo el proyecto.
- Las conclusiones estarán limitadas a las variables y registros disponibles en la copia utilizada del conjunto de datos.

### Decisiones pendientes para la Fase 2

Las estrategias definitivas de tratamiento de valores faltantes, valores atípicos, duplicados y transformaciones no se establecen en esta fase. Cada decisión será adoptada en la Fase 2 después de medir el problema, comparar alternativas y evaluar su efecto sobre los datos.e datos.

## 8. Configuración del entorno reproducible

El proyecto utiliza un entorno virtual de Python (`.venv`) con el propósito de aislar las dependencias utilizadas y facilitar la reproducción del análisis en otros equipos.

Las versiones efectivamente instaladas se registran en el archivo `requirements.txt`. Este archivo permite reconstruir el entorno mediante la instalación de las mismas dependencias utilizadas durante el desarrollo.

El entorno virtual local no forma parte del repositorio Git, ya que se encuentra excluido mediante `.gitignore`. Cada integrante puede crear su propio entorno e instalar las dependencias declaradas en `requirements.txt`.

Esta configuración cumple una función diferente del control de versiones: el entorno y las dependencias permiten **reproducir la ejecución**, mientras que Git/GitHub permiten mantener la **trazabilidad de los cambios** realizados durante el proyecto.

In [1]:
import sys
import platform

import pandas as pd
import numpy as np
import openpyxl

print("=== ENTORNO DE EJECUCIÓN ===")
print(f"Python     : {sys.version.split()[0]}")
print(f"Sistema    : {platform.system()} {platform.release()}")
print(f"Pandas     : {pd.__version__}")
print(f"NumPy      : {np.__version__}")
print(f"OpenPyXL   : {openpyxl.__version__}")

=== ENTORNO DE EJECUCIÓN ===
Python     : 3.11.9
Sistema    : Windows 10
Pandas     : 3.0.5
NumPy      : 2.4.6
OpenPyXL   : 3.1.5

### 8.1 Semilla de reproducibilidad

Se establece una semilla aleatoria fija para asegurar que cualquier operación estocástica incorporada posteriormente al proyecto pueda ser reproducida bajo las mismas condiciones.

In [2]:
SEED = 42
np.random.seed(SEED)

print(f"Semilla de reproducibilidad configurada: {SEED}")

Semilla de reproducibilidad configurada: 42

## 9. Fuente y ubicación del conjunto de datos

La copia del conjunto de datos utilizada por el proyecto se conserva en `data/raw/` sin modificaciones. Esta ubicación separa explícitamente los datos originales de los datos que serán procesados posteriormente en la Fase 2.

Para favorecer la reproducibilidad, el acceso al archivo se realiza mediante una ruta relativa respecto de la estructura del proyecto, evitando rutas absolutas asociadas a un computador específico.

La fecha de descarga de la copia utilizada será registrada en el `README.md`, permitiendo identificar el estado temporal de una fuente que puede actualizarse posteriormente.

In [3]:
from pathlib import Path

RUTA_DATOS = Path("../data/raw/Sancionatorios.xlsx")

print(f"Archivo definido: {RUTA_DATOS}")
print(f"¿El archivo existe?: {RUTA_DATOS.exists()}")

Archivo definido: ..\data\raw\Sancionatorios.xlsx
¿El archivo existe?: True

In [4]:
datos = pd.read_excel(RUTA_DATOS)

print("Carga del conjunto de datos completada correctamente.")
print(f"Número de registros : {datos.shape[0]:,}")
print(f"Número de variables : {datos.shape[1]}")

Carga del conjunto de datos completada correctamente.
Número de registros : 3,537
Número de variables : 19

### 9.1 Reconocimiento inicial del conjunto de datos

En esta etapa se realiza únicamente un reconocimiento estructural de la copia original del conjunto de datos. El propósito es verificar su correcta lectura e identificar sus dimensiones, variables y tipos generales.

No se realizan operaciones de eliminación, imputación, limpieza o transformación, ya que dichas decisiones corresponden a la Fase 2 y deberán estar sustentadas previamente por mediciones y evidencia.

In [5]:
datos.head()

,ProcesoSancionId,Expediente,ProcesoSancionTipoNombre,ProcesoSancionEstado,FechaInicio,FechaTermino,ConfirmaPdC,MultaTotalUTA,LinkSNIFA,UnidadFiscalizableId,Nombre,RegionNombre,ComunaNombre,Latitud,Longitud,CategoriaEconomicaNombre,SubCategoriaEconomicaNombre,LinkSNIFA_UF,FechaActualizacion
0,1,A-002-2013,Autodenuncia,En curso,27-03-2013,23-06-2026,No,7021.0,https://snifa.sma.gob.cl/Sancionatorio/Ficha/1...,1078,BARRICK - PASCUA LAMA,Región de Atacama,Alto del Carmen,-29.282648,-70.063014,Minería,Minera metálica,http://snifa.sma.gob.cl/UnidadFiscalizable/Fic...,12-09-26
1,2,F-002-2013,Fiscalización,Terminado - Sanción,01-04-2013,13-08-2013,No,94.0,https://snifa.sma.gob.cl/Sancionatorio/Ficha/2...,162,MALL PLAZA EGAÑA - LA REINA,Región Metropolitana,La Reina,-33.453000,-70.570000,Equipamiento,Centro comercial,http://snifa.sma.gob.cl/UnidadFiscalizable/Fic...,12-09-26
2,3,A-001-2013,Autodenuncia,Terminado - PDC Satisfactorio,08-02-2013,12-02-2014,Sí,NaN,https://snifa.sma.gob.cl/Sancionatorio/Ficha/3...,299,FAENA MINERA QUEBRADA BLANCA,Región de Tarapacá,Pica,-21.002000,-68.795800,Minería,Minera metálica,http://snifa.sma.gob.cl/UnidadFiscalizable/Fic...,12-09-26
3,4,D-004-2013,Denuncia,Terminado - Sanción,02-05-2013,11-10-2013,No,25.0,https://snifa.sma.gob.cl/Sancionatorio/Ficha/4...,2488,VERTEDERO DICHAM,Región de los Lagos,Chonchi,-42.627141,-73.841298,Saneamiento Ambiental,Vertedero,http://snifa.sma.gob.cl/UnidadFiscalizable/Fic...,12-09-26
4,5,F-003-2013,Fiscalización,Terminado - PDC Satisfactorio,08-05-2013,01-08-2014,Sí,NaN,https://snifa.sma.gob.cl/Sancionatorio/Ficha/5...,10480,CES FRANCISCO NORTE (RNA 110522),Región de Aysén del General Carlos Ibáñez del ...,Aysén,-44.506667,-73.610122,Pesca y Acuicultura,Centro de engorda de salmones,http://snifa.sma.gob.cl/UnidadFiscalizable/Fic...,12-09-26

In [6]:
print("Variables disponibles en el conjunto de datos:\n")

for i, columna in enumerate(datos.columns, start=1):
    print(f"{i:02d}. {columna}")

Variables disponibles en el conjunto de datos:

01. ProcesoSancionId
02. Expediente
03. ProcesoSancionTipoNombre
04. ProcesoSancionEstado
05. FechaInicio
06. FechaTermino
07. ConfirmaPdC
08. MultaTotalUTA
09. LinkSNIFA
10. UnidadFiscalizableId
11. Nombre
12. RegionNombre
13. ComunaNombre
14. Latitud
15. Longitud
16. CategoriaEconomicaNombre
17. SubCategoriaEconomicaNombre
18. LinkSNIFA_UF
19. FechaActualizacion

### 9.2 Tipos de datos detectados

A continuación se identifican los tipos de datos detectados automáticamente por Pandas para cada variable. Esta revisión permite reconocer la estructura técnica inicial del conjunto de datos sin realizar conversiones ni transformaciones.

La clasificación automática será considerada como un diagnóstico inicial. La naturaleza conceptual de cada variable será evaluada posteriormente, ya que el tipo detectado por una herramienta no necesariamente representa su significado analítico.

In [7]:
datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 3537 entries, 0 to 3536
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ProcesoSancionId             3537 non-null   int64
 1   Expediente                   3537 non-null   str
 2   ProcesoSancionTipoNombre     3537 non-null   str
 3   ProcesoSancionEstado         3537 non-null   str
 4   FechaInicio                  3537 non-null   str
 5   FechaTermino                 2106 non-null   str
 6   ConfirmaPdC                  3537 non-null   str
 7   MultaTotalUTA                1298 non-null   float64
 8   LinkSNIFA                    3537 non-null   str
 9   UnidadFiscalizableId         3537 non-null   int64
 10  Nombre                       3537 non-null   str
 11  RegionNombre                 3537 non-null   str
 12  ComunaNombre                 3537 non-null   str
 13  Latitud                      3498 non-null   float64
 14  Longitud                     3499 non-null   float64
 15  CategoriaEconomicaNombre     3521 non-null   str
 16  SubCategoriaEconomicaNombre  3521 non-null   str
 17  LinkSNIFA_UF                 3537 non-null   str
 18  FechaActualizacion           3537 non-null   str
dtypes: float64(3), int64(2), str(14)
memory usage: 525.2 KB

In [8]:
resumen_estructura = pd.DataFrame({
    "Variable": datos.columns,
    "Tipo_detectado": datos.dtypes.astype(str).values,
    "No_nulos": datos.notna().sum().values,
    "Nulos": datos.isna().sum().values
})

resumen_estructura

                       Variable Tipo_detectado  No_nulos  Nulos
0              ProcesoSancionId          int64      3537      0
1                    Expediente            str      3537      0
2      ProcesoSancionTipoNombre            str      3537      0
3          ProcesoSancionEstado            str      3537      0
4                   FechaInicio            str      3537      0
5                  FechaTermino            str      2106   1431
6                   ConfirmaPdC            str      3537      0
7                 MultaTotalUTA        float64      1298   2239
8                     LinkSNIFA            str      3537      0
9          UnidadFiscalizableId          int64      3537      0
10                       Nombre            str      3537      0
11                 RegionNombre            str      3537      0
12                 ComunaNombre            str      3537      0
13                      Latitud        float64      3498     39
14                     Longitud        float64      3499     38
15     CategoriaEconomicaNombre            str      3521     16
16  SubCategoriaEconomicaNombre            str      3521     16
17                 LinkSNIFA_UF            str      3537      0
18           FechaActualizacion            str      3537      0

### 9.3 Observaciones del reconocimiento inicial

El conjunto de datos cargado contiene **3.537 registros y 19 variables**. En esta revisión estructural se observa que la mayoría de las variables presenta información completa, aunque algunas contienen valores ausentes.

En particular, `MultaTotalUTA`, variable central para la pregunta de investigación, presenta 1.298 valores no nulos y 2.239 valores ausentes. Esto equivale aproximadamente al **63,3 % del conjunto de datos total**.

Este resultado no permite concluir por sí solo que exista un problema de calidad de datos. De acuerdo con la naturaleza del conjunto analizado, la ausencia de `MultaTotalUTA` puede estar asociada a procedimientos que no presentan una multa aplicable. Por esta razón, el tratamiento de estos valores no se realizará en la Fase 1.

En la Fase 2 se deberá analizar el universo pertinente para la variable `MultaTotalUTA`, medir nuevamente la proporción de valores ausentes y justificar cualquier decisión de filtrado, tratamiento o transformación a partir de dicha evidencia.

Asimismo, se observa que variables como `FechaInicio`, `FechaTermino` y `FechaActualizacion` fueron detectadas inicialmente como texto (`str`). Su eventual conversión a tipos de fecha será evaluada y justificada en la Fase 2, evitando modificar la estructura original durante esta etapa.

In [9]:
nulos_multa = datos["MultaTotalUTA"].isna().sum()
total_registros = len(datos)
porcentaje_nulos_multa = (nulos_multa / total_registros) * 100

print("=== RECONOCIMIENTO DE MultaTotalUTA ===")
print(f"Total de registros       : {total_registros:,}")
print(f"Valores presentes        : {datos['MultaTotalUTA'].notna().sum():,}")
print(f"Valores ausentes         : {nulos_multa:,}")
print(f"Porcentaje de ausentes   : {porcentaje_nulos_multa:.2f}%")

=== RECONOCIMIENTO DE MultaTotalUTA ===
Total de registros       : 3,537
Valores presentes        : 1,298
Valores ausentes         : 2,239
Porcentaje de ausentes   : 63.30%

### 9.4 Clasificación conceptual de variables

Los tipos detectados automáticamente por Pandas representan la forma en que los datos son almacenados computacionalmente, pero no determinan por sí solos su naturaleza analítica.

Por ejemplo, `RegionNombre` y `CategoriaEconomicaNombre` son tratadas conceptualmente como variables categóricas nominales, ya que sus valores representan categorías sin un orden inherente. Esta clasificación se establece considerando el significado de las variables y no únicamente criterios automáticos basados en el número de valores diferentes.

La distinción entre tipo computacional y naturaleza analítica será considerada durante las decisiones de procesamiento y análisis de las fases posteriores.

## 10. Reproducibilidad, trazabilidad y documentación

El proyecto distingue tres componentes complementarios que permiten desarrollar un flujo de Ciencia de Datos técnicamente verificable:

### Reproducibilidad
Corresponde a la capacidad de reconstruir el entorno y volver a ejecutar el análisis bajo condiciones equivalentes. Se sustenta mediante el ambiente virtual, el archivo `requirements.txt`, el registro de versiones, el uso de rutas relativas y las instrucciones de ejecución documentadas en el `README.md`.

### Trazabilidad
Corresponde al registro de la evolución del proyecto. Git y GitHub permiten identificar los cambios realizados, su autoría y el momento en que fueron incorporados mediante commits descriptivos y progresivos.

### Documentación
Corresponde a la explicación técnica de qué se realiza, por qué se realiza y qué evidencia respalda cada decisión. Las celdas Markdown documentan objetivos, supuestos, decisiones y justificaciones; el código produce evidencia verificable; el README explica cómo reproducir el proyecto; y el informe técnico integra y comunica los resultados del proceso.

### 10.1 Función de los artefactos del proyecto

| Artefacto | Función principal |
|---|---|
| `.venv` | Aísla localmente el entorno de ejecución del proyecto. |
| `requirements.txt` | Registra las dependencias y versiones necesarias para reconstruir el entorno. |
| `README.md` | Documenta el proyecto y proporciona instrucciones para reproducir y ejecutar el trabajo. |
| Notebook | Integra narrativa, código ejecutable, resultados y evidencia técnica. |
| Celda Markdown | Explica objetivos, decisiones, supuestos e interpretación de resultados. |
| Celda de código | Ejecuta operaciones y produce resultados verificables. |
| Commit Git | Registra un cambio concreto y permite reconstruir la evolución del proyecto. |
| GitHub | Centraliza el repositorio y permite colaboración y trazabilidad del trabajo grupal. |
| Informe técnico | Integra, justifica y comunica formalmente las decisiones, evidencias y resultados del proyecto. |

## 11. Articulación con las fases del proyecto

El proyecto se desarrolla progresivamente en cuatro fases relacionadas entre sí:

**Fase 1 — Definición y reproducibilidad:**  
Define la problemática, pregunta de investigación, objetivos, alcance, supuestos, fuente de datos y entorno reproducible. Además, realiza el reconocimiento estructural inicial del conjunto de datos sin modificarlo.

**Fase 2 — Exploración, preprocesamiento y validación:**  
Profundizará el diagnóstico de calidad de los datos y evaluará valores faltantes, duplicados, tipos de datos, posibles valores atípicos y otras inconsistencias. Las decisiones de limpieza y transformación serán justificadas mediante mediciones previas y sus efectos serán posteriormente validados.

**Fase 3 — Análisis y visualización:**  
Utilizará el conjunto de datos procesado y validado para estudiar las relaciones entre `MultaTotalUTA` y las variables explicativas seleccionadas, desarrollando visualizaciones y análisis coherentes con la pregunta de investigación.

**Fase 4 — Integración y comunicación de resultados:**  
Integrará los resultados obtenidos, las evidencias y las conclusiones del proyecto, manteniendo la correspondencia entre problemática, metodología, análisis y resultados.

## 12. Conclusiones de la Fase 1

La Fase 1 permitió establecer la base conceptual y técnica del proyecto, definiendo la problemática, la pregunta central, los objetivos, el alcance, los supuestos y las decisiones pendientes.

Se configuró un entorno reproducible basado en Python y un ambiente virtual con dependencias versionadas, mientras que Git/GitHub proporciona la trazabilidad de la evolución del proyecto.

El conjunto de datos original fue incorporado sin modificaciones y su reconocimiento inicial confirmó 3.537 registros y 19 variables. La variable de interés `MultaTotalUTA` presenta 2.239 valores ausentes, equivalentes aproximadamente al 63,3 % del conjunto total. Este resultado no será interpretado automáticamente como un problema de calidad, sino que será analizado en la Fase 2 considerando el universo de procedimientos al cual resulta aplicable una multa.

Por tanto, esta fase no adopta decisiones de limpieza o transformación. Estas serán determinadas en la Fase 2 a partir de evidencia cuantitativa, manteniendo como principio metodológico medir primero, decidir después y documentar la justificación de cada intervención.